### PR TITLE
Handle multi-region SNS

### PR DESCRIPTION
**Pull request by gws**
# Overview

The motivation for this PR is to support AWS SES (Simple Email Service) in multiple regions. Currently, the AWS region is configured by the `turbovote-http-api` service. When receiving bounce and complaint notifications via SNS (Simple Notification Service), the message is signed with a region-specific key. The configured AWS region is currently used to validate the message signature. However, when receiving SNS messages from other regions, the signature validation fails. For instance, an SNS message signed with a `us-west-2` key will fail validation with a (configured) `us-east-1` SNS message validation class.

This PR improves the situation by validating the SNS message received dynamically based on the region of the originating SNS topic.

# Other improvements

- Tests were focused on re-validating logic that was already part of the AWS SDK rather than testing application logic, and further, they were causing side effects (reaching out to AWS for the PEM-encoded public key to validate signatures). That test had to be commented out once the PEM-encoded key was rotated and disappeared. Instead, we test a similar code path as before, but with the AWS Java SDK call isolated to a function which can be replaced in testing, and used in production knowing it has been tested by AWS.
- Previously, we parsed JSON prior to validating its signature and then had to re-encode and re-decode it to work with the AWS Java SDK. This was both wasteful computationally and also not setting a great example for others - signed messages should always be verified _before_ being parsed. Now we delegate that parsing and validation entirely to the AWS Java SDK.

# Testing

SNS message confirmation:
```
Apr 01 12:08:07 working-1.kube.democracy.works-development-turbovote-http-api-f4964bcc9-hn5vk turbovote-http-api 19:08:06.064 INFO  [io.pedestal.http] (qtp953797060-27) {:msg "POST /election-notifications/unsubscribe-aws", :line 80}
Apr 01 12:08:08 working-1.kube.democracy.works-development-turbovote-http-api-f4964bcc9-hn5vk turbovote-http-api 19:08:06.635 DEBUG [turbovote-http-api.sns-utils] (qtp953797060-27) Confirming SNS subscription
```

SNS message processing (bounce message):
```
Apr 01 12:11:27 working-1.kube.democracy.works-development-turbovote-http-api-f4964bcc9-d5r2s turbovote-http-api 19:11:25.948 INFO  [io.pedestal.http] (qtp953797060-31) {:msg "POST /election-notifications/unsubscribe-aws", :line 80}
Apr 01 12:11:27 working-1.kube.democracy.works-development-turbovote-http-api-f4964bcc9-d5r2s turbovote-http-api 19:11:26.561 DEBUG [turbovote-http-api.handlers.unsubscribe-aws] (qtp953797060-31) Unsubscribing emails ["bounce@simulator.amazonses.com"]
Apr 01 12:11:28 working-1.kube.democracy.works-development-election-notification-works-5475fb7f7-gnfc4 election-notification-works 19:11:26.564 DEBUG [election-notification-works.handlers] (async-thread-macro-32) Deleting email notys for bounce@simulator.amazonses.com
```

### CODE REVIEW

**Comment by gws** [comment]
I'm tagging people who were involved in the incident response last Friday, as this is a necessary prerequisite for setting up a backup AWS region, something we identified as useful for the future.

**Comment by dzcode** [comment]
This looks great, thanks Gordon!

**Comment by eggsyntax** [comment]
> Previously, we parsed JSON prior to validating its signature and then had to re-encode and re-decode it to work with the AWS Java SDK. 

That was a really hideous approach, but I couldn't for the life of me find a way around it at the time. There's a comment at the bottom of `turbovote-http-api.handlers.unsubscribe-aws` explaining why it's done that way, which can now be deleted -- I'll get rid of it if you don't want to do it in this PR.

**Comment by gws** [comment]
@eggsyntax No problem, it makes sense to take that out as part of this PR :+1:

**Pull request merged**
